language: python

os:
  - linux
  - osx

env: TOXENV=py

matrix:
  include:
    - env: TOXENV=manifest
    - env: TOXENV=pyroma
  allow_failures:
    - os: osx
    - python: "3.5"

python:
  - "3.6"
  - "3.5"

install: pip install tox pytest-cov coveralls

script: tox

after_success: coveralls
