language: python

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

python:
  - "3.5"
  - "3.6"

install:
  - pip install tox pytest-cov coveralls
  # TEMP: fixes weird issue caused by Gensim
  - pip install google-compute-engine
  # TEMP: fixes weird issue caused by msgpack
  - pip install msgpack==0.5.6

script: tox

after_success: coveralls
