language: python

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

python:
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  # TEMP: fixes weird issue caused by Gensim
  - pip install google-compute-engine
  # TEMP: fixes weird issue caused by msgpack
  - pip install msgpack==0.5.6

script:
  - pytest --cov=saber -v

after_success: coveralls
