language: python

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

python:
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls

script:
  - py.test --cov=saber 

after_success: coveralls
