language: python

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls

script:
  - PYTHONPATH=./kari py.test

after_success:
  - coveralls
